apiVersion: v2
appVersion: "1.0"
description: ML Inference Service Template for GPU workloads using Ollama.
name: ollama-inference-load
version: 1.0.1
maintainers:
  - name: delProfundo
    email: bruno@hypermedia.au
