---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.serviceName }}
    catalog: {{ .Values.serviceCatalog }}
spec:
  ports:
    {{- range .Values.container.containerPorts }}
    - name: {{ .portName }}
      protocol: {{ .protocol }}
      port: {{ .servicePort }}
      targetPort: {{ .portNumber }}
    {{- end }}
  type: ClusterIP
  selector:
    app: {{ .Values.serviceName }}
