{{- if .Values.ingress.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.serviceName }}-gateway
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.serviceName }}
    catalog: {{ .Values.serviceCatalog }}
spec:
  gatewayClassName: istio
  listeners:
    - name: https
      hostname: {{ .Values.ingress.host }}
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: Same
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Values.serviceName }}-tls
{{- end }}
