{{- if .Values.ingress.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.serviceName }}-route
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.serviceName }}
    catalog: {{ .Values.serviceCatalog }}
spec:
  parentRefs:
    - name: {{ .Values.serviceName }}-gateway
  hostnames:
    - {{ .Values.ingress.host }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Values.serviceName }}
          port: {{ .Values.service.port }}
{{- end }}
