{{- if .Values.container.secrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.serviceName }}-secrets
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1s
  secretStoreRef:
    selector:
      {{- toYaml .Values.container.secretStore.selector | nindent 4 }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.serviceName }}-secrets
    creationPolicy: Owner
  data:
    {{- range .Values.container.secrets }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .vaultPath }}
        property: value
    {{- end }}
{{- end }}
